// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kecbiuksxklaqzjcsdss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlY2JpdWtzeGtsYXF6amNzZHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTQ0NTQsImV4cCI6MjA2MzY5MDQ1NH0.f41xLEKj1ofLt4LJgVr3PguYO18tHmrIdNrgdALSqJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);